### Get all posts
@baseUrl = http://localhost:8080

GET {{baseUrl}}/post
Content-Type: application/json

### Get post by ID
GET {{baseUrl}}/post/676ac84f0d029b8c81866b06
Content-Type: application/json

### Get post by sender ID
GET {{baseUrl}}/post?sender=4
Content-Type: application/json

### Add new post
POST {{baseUrl}}/post
Content-Type: application/json

{
    "title": "Test Post Title",
    "body": "Test post body",
    "image": "Test post image URL",
    "userId": 4
}

### Update an existing post
PUT {{baseUrl}}/post/6782c609414828b5e2a37e43
Content-Type: application/json

{
    "title": "Replacement Post Title",
    "body": "Replacement post body",
    "userId": 4
}


//comments requests
### Get all comments
GET http://localhost:8080/comment
Content-Type: application/json

### Get comment by ID
GET http://localhost:8080/comment/6786dfa5fe4909664eb0a4b8
Content-Type: application/json

### Get comments by post ID
GET http://localhost:8080/comment/post/1
Content-Type: application/json

### Add new comment
POST http://localhost:8080/comment
Content-Type: application/json

{
    "body": "This is a test comment.",
    "text": "This is a test comment.",
    "userId": 4,
    "postId": 1
}


### Update an existing comment
PUT http://localhost:8080/comment/6786dfa5fe4909664eb0a4b6
Content-Type: application/json

{
    "body": "Updated comment body",
    "text": "Updated comment body",
    "userId": 4,
    "postId": 1
}



### Delete a comment
DELETE http://localhost:8080/comment/6786dfa5fe4909664eb0a4b6
Content-Type: application/json


